name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          template: terminal
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Paris
          plugin_habits: true
          plugin_lines: true
          plugin_isocalendar: true
          plugin_code: true
          plugin_rss: true
          plugin_rss_source: https://tarneo.fr/posts/index.xml
          plugin_rss_limit: 5
